using Bars.Mvvm.FluidApi.Common;
using System.Text;

namespace Bars.Mvvm.Resource.Generator;

internal class BarTemplateSelectorAttributeCodeGenerator
{
    private const string _attributeNameSpace = "ActiproSoftware.Windows.Controls.Bars.Mvvm";
    private const string _attributeName = "BarTemplateSelector";
    public const string AttributeClassName = $"{_attributeName}Attribute";
    public const string FullyQualifiedAttributeName = $"{_attributeNameSpace}.{AttributeClassName}";

    public static BarTemplateSelectorAttributeCodeGenerator Instance { get; } = new();

    public static string Generate()
    {
        StringBuilder attrBuilder = new();
        attrBuilder.AppendLine("// <auto-generated/>");
        attrBuilder.AppendLine("using System;");
        attrBuilder.AppendLine("using Microsoft.CodeAnalysis;");
        attrBuilder.AppendLine($"namespace {_attributeNameSpace};");
        attrBuilder.AppendLine(
            "[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]");

        attrBuilder.AppendLine($"internal sealed class {AttributeClassName} : Attribute");
        attrBuilder.AppendLineStartBracket(0);
        attrBuilder.AppendLineWithIndent(1, $"public {AttributeClassName}()");
        attrBuilder.AppendLineStartBracket(1);
        attrBuilder.AppendLineEndBracket(1);
        attrBuilder.AppendLineEndBracket(0);
        return attrBuilder.ToString();
    }
}
